[rpc]
host="http://127.0.0.1:1234"
admin="admin"
password="123"


[db]
# mysql | sqlserver
dbtype="mysql"
user="root"
password="kahfxwxsx113"
address="127.0.0.1:3306"
dbname="sync"

[log]
# console=12 | file=11
mode=12
# debug=0 | info=1 | warn=2 | fail=3 | error=4 | email=5
level=0
path="logs"

[email]
title="qitmeer-sync"
user=""
pass=""
host=""
port=""
to=[""]

[verify]
utxo=true
fees=true
interval=1
version="0.9"

[resources]
cpu-number=16
gc-percent=20

