[[rpcs]]
host="http://203.86.236.20/mainnet"
admin="admin"
password="123"
[[rpcs]]
host="http://203.86.236.20/mainnet"
admin="qitmeer"
password="123"
[[rpcs]]
host="http://203.86.236.20/mainnet"
admin="qitmeer"
password="123"


[db]
# mysql | sqlserver
dbtype="mysql"
user="client"
password="Qitmeer@user.client"
address="203.86.236.20:3306"
dbname="mainnet"

[log]
# console=12 | file=11
mode=12
# debug=0 | info=1 | warn=2 | fail=3 | error=4 | email=5
level=0
path="logs"

[email]
title="qitmeer-sync"
user=""
pass=""
host=""
port=""
to=[""]

[verify]
utxo=false
fees=false
interval=10
version="0.10"

[resources]
cpu-number=16
gc-percent=20

